version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run: 
          name: Chrome
          executor: cypress/browsers-chrome73-ff68
          start: npm run dev
          wait-on: http://localhost:8080
          record: true
          command: npx cypress run --record --key 4b0445c1-a9b9-4b2e-8093-271d9ad33210
          group: chrome
          browser: chrome
      - cypress/run:
          name: Firefox
          executor: cypress/browsers-chrome73-ff68
          start: npm run dev
          wait-on: http://localhost:8080
          record: true
          command: npx cypress run --record --key 4b0445c1-a9b9-4b2e-8093-271d9ad33210
          group: firefox-critical-path
          browser: firefox
          